import React from 'react';
import { 
  Activity, 
  Scissors, 
  Heart, 
  Brain, 
  FileText, 
  Baby, 
  HeartHandshake, 
  Clock, 
  Eye, 
  ShieldAlert, 
  AlertCircle, 
  ShoppingBag, 
  Truck, 
  Home,
  Phone,
  MapPin,
  Mail,
  Calendar,
  Star,
  ChevronRight,
  ChevronLeft,
  CheckCircle2,
  Check,
  Plus,
  Trash2,
  Edit,
  Loader,
  Menu,
  X,
  Lock,
  Settings,
  Users,
  LayoutDashboard,
  Briefcase,
  FilePlus,
  LogOut,
  Database,
  Image as ImageIcon,
  Search,
  ThumbsUp,
  Award,
  MessageSquare,
  Building,
  Map,
  PlusCircle,
  HelpCircle,
  Filter,
  CheckSquare
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  Activity,
  Scissors,
  Heart,
  Brain,
  FileText,
  Baby,
  HeartHandshake,
  Clock,
  Eye,
  ShieldAlert,
  AlertCircle,
  ShoppingBag,
  Truck,
  Home,
  Phone,
  MapPin,
  Mail,
  Calendar,
  Star,
  ChevronRight,
  ChevronLeft,
  CheckCircle2,
  Check,
  Plus,
  Trash2,
  Edit,
  Loader,
  Menu,
  X,
  Lock,
  Settings,
  Users,
  LayoutDashboard,
  Briefcase,
  FilePlus,
  LogOut,
  Database,
  ImageIcon,
  Search,
  ThumbsUp,
  Award,
  MessageSquare,
  Building,
  Map,
  PlusCircle,
  HelpCircle,
  Filter,
  CheckSquare
};

interface LucideIconProps {
  name: string;
  className?: string;
  fallback?: string;
}

export const LucideIcon: React.FC<LucideIconProps> = ({ name, className, fallback = 'Activity' }) => {
  // Normalize key name to match our map keys (e.g. 'Activity', 'Scissors', 'Heart')
  const IconComponent = iconMap[name] || iconMap[fallback] || Activity;
  return <IconComponent className={className} />;
};
